-- Actualizar bpc_process y bpc_e2e para los 524 escenarios de Finance
-- Ejecutar en Supabase SQL Editor

-- Primero agregar las columnas si no existen
ALTER TABLE scenario_selection ADD COLUMN IF NOT EXISTS bpc_process text;
ALTER TABLE scenario_selection ADD COLUMN IF NOT EXISTS bpc_e2e text;

UPDATE scenario_selection SET bpc_process = 'Classify assets', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.010.100';
UPDATE scenario_selection SET bpc_process = 'Classify assets', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.010.200';
UPDATE scenario_selection SET bpc_process = 'Define leasing policies', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.030.100';
UPDATE scenario_selection SET bpc_process = 'Define leasing policies', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.030.200';
UPDATE scenario_selection SET bpc_process = 'Define leasing policies', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.030.300';
UPDATE scenario_selection SET bpc_process = 'Define asset accounting books', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.060.100';
UPDATE scenario_selection SET bpc_process = 'Define asset accounting books', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.060.200';
UPDATE scenario_selection SET bpc_process = 'Define depreciation and amortization policies', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.080.100';
UPDATE scenario_selection SET bpc_process = 'Define depreciation and amortization policies', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.080.200';
UPDATE scenario_selection SET bpc_process = 'Define depreciation and amortization policies', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.080.400';
UPDATE scenario_selection SET bpc_process = 'Define depreciation and amortization policies', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.080.500';
UPDATE scenario_selection SET bpc_process = 'Define depreciation and amortization policies', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.080.600';
UPDATE scenario_selection SET bpc_process = 'Define depreciation and amortization policies', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.080.700';
UPDATE scenario_selection SET bpc_process = 'Define depreciation and amortization policies', bpc_e2e = 'Define asset strategy' WHERE scenario_id = '10.05.080.800';
UPDATE scenario_selection SET bpc_process = 'Plan fixed assets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.100.100';
UPDATE scenario_selection SET bpc_process = 'Plan asset leases', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.150.100';
UPDATE scenario_selection SET bpc_process = 'Budget fixed assets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.200.100';
UPDATE scenario_selection SET bpc_process = 'Budget fixed assets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.200.200';
UPDATE scenario_selection SET bpc_process = 'Budget fixed assets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.200.300';
UPDATE scenario_selection SET bpc_process = 'Budget fixed assets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.200.400';
UPDATE scenario_selection SET bpc_process = 'Budget fixed assets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.200.800';
UPDATE scenario_selection SET bpc_process = 'Budget asset leases', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.250.100';
UPDATE scenario_selection SET bpc_process = 'Budget asset leases', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.250.200';
UPDATE scenario_selection SET bpc_process = 'Budget asset leases', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.250.300';
UPDATE scenario_selection SET bpc_process = 'Budget asset leases', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.250.600';
UPDATE scenario_selection SET bpc_process = 'Reallocate asset budgets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.275.100';
UPDATE scenario_selection SET bpc_process = 'Reallocate asset budgets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.275.200';
UPDATE scenario_selection SET bpc_process = 'Reallocate asset budgets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.275.300';
UPDATE scenario_selection SET bpc_process = 'Reallocate asset budgets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.275.400';
UPDATE scenario_selection SET bpc_process = 'Lease assets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.600.100';
UPDATE scenario_selection SET bpc_process = 'Lease assets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.600.200';
UPDATE scenario_selection SET bpc_process = 'Lease assets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.600.300';
UPDATE scenario_selection SET bpc_process = 'Lease assets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.600.400';
UPDATE scenario_selection SET bpc_process = 'Lease assets', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.600.500';
UPDATE scenario_selection SET bpc_process = 'Record fixed asset acquisitions', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.800.100';
UPDATE scenario_selection SET bpc_process = 'Record fixed asset acquisitions', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.800.200';
UPDATE scenario_selection SET bpc_process = 'Record fixed asset acquisitions', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.800.300';
UPDATE scenario_selection SET bpc_process = 'Record fixed asset acquisitions', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.800.400';
UPDATE scenario_selection SET bpc_process = 'Record fixed asset acquisitions', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.800.500';
UPDATE scenario_selection SET bpc_process = 'Record asset lease right-of-use', bpc_e2e = 'Acquire assets' WHERE scenario_id = '10.20.900.100';
UPDATE scenario_selection SET bpc_process = 'Maintain fixed assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.025.100';
UPDATE scenario_selection SET bpc_process = 'Maintain fixed assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.025.200';
UPDATE scenario_selection SET bpc_process = 'Maintain fixed assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.025.300';
UPDATE scenario_selection SET bpc_process = 'Maintain fixed assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.025.400';
UPDATE scenario_selection SET bpc_process = 'Maintain asset leases', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.035.100';
UPDATE scenario_selection SET bpc_process = 'Maintain asset leases', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.035.200';
UPDATE scenario_selection SET bpc_process = 'Maintain asset leases', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.035.300';
UPDATE scenario_selection SET bpc_process = 'Make payments on asset leases', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.060.100';
UPDATE scenario_selection SET bpc_process = 'Make payments on asset leases', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.060.200';
UPDATE scenario_selection SET bpc_process = 'Make payments on asset leases', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.060.400';
UPDATE scenario_selection SET bpc_process = 'Make payments on asset leases', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.060.500';
UPDATE scenario_selection SET bpc_process = 'Revalue and adjust assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.090.100';
UPDATE scenario_selection SET bpc_process = 'Revalue and adjust assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.090.200';
UPDATE scenario_selection SET bpc_process = 'Revalue and adjust assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.090.300';
UPDATE scenario_selection SET bpc_process = 'Revalue and adjust assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.090.400';
UPDATE scenario_selection SET bpc_process = 'Revalue and adjust assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.090.500';
UPDATE scenario_selection SET bpc_process = 'Revalue and adjust assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.090.600';
UPDATE scenario_selection SET bpc_process = 'Revalue and adjust assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.090.700';
UPDATE scenario_selection SET bpc_process = 'Depreciate assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.100.100';
UPDATE scenario_selection SET bpc_process = 'Depreciate assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.100.200';
UPDATE scenario_selection SET bpc_process = 'Depreciate assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.100.300';
UPDATE scenario_selection SET bpc_process = 'Depreciate assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.100.400';
UPDATE scenario_selection SET bpc_process = 'Depreciate assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.100.500';
UPDATE scenario_selection SET bpc_process = 'Depreciate assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.100.600';
UPDATE scenario_selection SET bpc_process = 'Depreciate assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.100.700';
UPDATE scenario_selection SET bpc_process = 'Depreciate assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.100.800';
UPDATE scenario_selection SET bpc_process = 'Insure assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.200.100';
UPDATE scenario_selection SET bpc_process = 'Insure assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.200.200';
UPDATE scenario_selection SET bpc_process = 'Insure assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.200.300';
UPDATE scenario_selection SET bpc_process = 'Transfer assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.300.300';
UPDATE scenario_selection SET bpc_process = 'Transfer assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.300.400';
UPDATE scenario_selection SET bpc_process = 'Transfer assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.300.500';
UPDATE scenario_selection SET bpc_process = 'Transfer assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.300.600';
UPDATE scenario_selection SET bpc_process = 'Transfer assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.300.700';
UPDATE scenario_selection SET bpc_process = 'Improve assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.400.100';
UPDATE scenario_selection SET bpc_process = 'Improve assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.400.200';
UPDATE scenario_selection SET bpc_process = 'Improve assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.400.300';
UPDATE scenario_selection SET bpc_process = 'Improve assets', bpc_e2e = 'Manage active assets' WHERE scenario_id = '10.40.400.400';
UPDATE scenario_selection SET bpc_process = 'Budget asset maintenance', bpc_e2e = 'Perform asset maintenance' WHERE scenario_id = '10.50.010.020';
UPDATE scenario_selection SET bpc_process = 'Budget asset maintenance', bpc_e2e = 'Perform asset maintenance' WHERE scenario_id = '10.50.010.030';
UPDATE scenario_selection SET bpc_process = 'Scrap an asset', bpc_e2e = 'Dispose of assets' WHERE scenario_id = '10.60.020.100';
UPDATE scenario_selection SET bpc_process = 'Sell an asset', bpc_e2e = 'Dispose of assets' WHERE scenario_id = '10.60.030.100';
UPDATE scenario_selection SET bpc_process = 'Sell an asset', bpc_e2e = 'Dispose of assets' WHERE scenario_id = '10.60.030.200';
UPDATE scenario_selection SET bpc_process = 'Sell an asset', bpc_e2e = 'Dispose of assets' WHERE scenario_id = '10.60.030.300';
UPDATE scenario_selection SET bpc_process = 'Retire assets', bpc_e2e = 'Dispose of assets' WHERE scenario_id = '10.60.050.100';
UPDATE scenario_selection SET bpc_process = 'Retire assets', bpc_e2e = 'Dispose of assets' WHERE scenario_id = '10.60.050.200';
UPDATE scenario_selection SET bpc_process = 'Retire assets', bpc_e2e = 'Dispose of assets' WHERE scenario_id = '10.60.050.300';
UPDATE scenario_selection SET bpc_process = 'Retire assets', bpc_e2e = 'Dispose of assets' WHERE scenario_id = '10.60.050.400';
UPDATE scenario_selection SET bpc_process = 'Decommission assets', bpc_e2e = 'Dispose of assets' WHERE scenario_id = '10.60.060.100';
UPDATE scenario_selection SET bpc_process = 'Decommission assets', bpc_e2e = 'Dispose of assets' WHERE scenario_id = '10.60.060.200';
UPDATE scenario_selection SET bpc_process = 'Decommission assets', bpc_e2e = 'Dispose of assets' WHERE scenario_id = '10.60.060.300';
UPDATE scenario_selection SET bpc_process = 'Monitor asset inventory', bpc_e2e = 'Analyze assets' WHERE scenario_id = '10.70.010.100';
UPDATE scenario_selection SET bpc_process = 'Monitor asset inventory', bpc_e2e = 'Analyze assets' WHERE scenario_id = '10.70.010.200';
UPDATE scenario_selection SET bpc_process = 'Analyze asset leases', bpc_e2e = 'Analyze assets' WHERE scenario_id = '10.70.020.100';
UPDATE scenario_selection SET bpc_process = 'Analyze asset leases', bpc_e2e = 'Analyze assets' WHERE scenario_id = '10.70.020.200';
UPDATE scenario_selection SET bpc_process = 'Analyze fixed assets', bpc_e2e = 'Analyze assets' WHERE scenario_id = '10.70.025.100';
UPDATE scenario_selection SET bpc_process = 'Analyze fixed assets', bpc_e2e = 'Analyze assets' WHERE scenario_id = '10.70.025.200';
UPDATE scenario_selection SET bpc_process = 'Analyze fixed assets', bpc_e2e = 'Analyze assets' WHERE scenario_id = '10.70.025.300';
UPDATE scenario_selection SET bpc_process = 'Analyze fixed assets', bpc_e2e = 'Analyze assets' WHERE scenario_id = '10.70.025.400';
UPDATE scenario_selection SET bpc_process = 'Reconcile asset subledger', bpc_e2e = 'Analyze assets' WHERE scenario_id = '10.70.060.100';
UPDATE scenario_selection SET bpc_process = 'Reconcile asset subledger', bpc_e2e = 'Analyze assets' WHERE scenario_id = '10.70.060.200';
UPDATE scenario_selection SET bpc_process = 'Reconcile asset subledger', bpc_e2e = 'Analyze assets' WHERE scenario_id = '10.70.060.400';
UPDATE scenario_selection SET bpc_process = 'Analyze product profitability', bpc_e2e = 'Analyze product performance' WHERE scenario_id = '40.90.300.300';
UPDATE scenario_selection SET bpc_process = 'Conduct current state analysis', bpc_e2e = 'Develop business strategy' WHERE scenario_id = '50.15.100.100';
UPDATE scenario_selection SET bpc_process = 'Develop scenario and contingency plans', bpc_e2e = 'Develop business strategy' WHERE scenario_id = '50.15.600.100';
UPDATE scenario_selection SET bpc_process = 'Plan workforce capacity', bpc_e2e = 'Conduct sales and operations planning' WHERE scenario_id = '50.25.700.200';
UPDATE scenario_selection SET bpc_process = 'Plan demand consensus', bpc_e2e = 'Conduct sales and operations planning' WHERE scenario_id = '50.25.650.100';
UPDATE scenario_selection SET bpc_process = 'Plan risks and opportunities', bpc_e2e = 'Conduct sales and operations planning' WHERE scenario_id = '50.25.775.100';
UPDATE scenario_selection SET bpc_process = 'Develop budgets', bpc_e2e = 'Conduct financial planning' WHERE scenario_id = '50.20.100.100';
UPDATE scenario_selection SET bpc_process = 'Develop budgets', bpc_e2e = 'Conduct financial planning' WHERE scenario_id = '50.20.100.200';
UPDATE scenario_selection SET bpc_process = 'Forecast revenue', bpc_e2e = 'Conduct financial planning' WHERE scenario_id = '50.20.200.100';
UPDATE scenario_selection SET bpc_process = 'Forecast revenue', bpc_e2e = 'Conduct financial planning' WHERE scenario_id = '50.20.200.200';
UPDATE scenario_selection SET bpc_process = 'Plan capital allocation and investments', bpc_e2e = 'Conduct financial planning' WHERE scenario_id = '50.20.300.100';
UPDATE scenario_selection SET bpc_process = 'Plan capital allocation and investments', bpc_e2e = 'Conduct financial planning' WHERE scenario_id = '50.20.300.200';
UPDATE scenario_selection SET bpc_process = 'Plan operational allocation and investments', bpc_e2e = 'Conduct financial planning' WHERE scenario_id = '50.20.400.400';
UPDATE scenario_selection SET bpc_process = 'Measure business performance', bpc_e2e = 'Analyze business performance' WHERE scenario_id = '50.65.100.100';
UPDATE scenario_selection SET bpc_process = 'Develop continuous improvement initiatives', bpc_e2e = 'Analyze business performance' WHERE scenario_id = '50.65.300.100';
UPDATE scenario_selection SET bpc_process = 'Measure goal achievement', bpc_e2e = 'Analyze business performance' WHERE scenario_id = '50.65.500.100';
UPDATE scenario_selection SET bpc_process = 'Monitor financial performance', bpc_e2e = 'Analyze business performance' WHERE scenario_id = '50.65.700.100';
UPDATE scenario_selection SET bpc_process = 'Define human resources policies', bpc_e2e = 'Develop people strategy' WHERE scenario_id = '55.05.030.300';
UPDATE scenario_selection SET bpc_process = 'Define expense policies', bpc_e2e = 'Develop people strategy' WHERE scenario_id = '55.05.050.100';
UPDATE scenario_selection SET bpc_process = 'Budget workforce', bpc_e2e = 'Recruit and onboard talent' WHERE scenario_id = '55.10.040.100';
UPDATE scenario_selection SET bpc_process = 'Budget workforce', bpc_e2e = 'Recruit and onboard talent' WHERE scenario_id = '55.10.040.200';
UPDATE scenario_selection SET bpc_process = 'Request travel', bpc_e2e = 'Manage time and attendance' WHERE scenario_id = '55.50.100.100';
UPDATE scenario_selection SET bpc_process = 'Manage employee travel', bpc_e2e = 'Manage time and attendance' WHERE scenario_id = '55.50.200.100';
UPDATE scenario_selection SET bpc_process = 'Manage employee travel', bpc_e2e = 'Manage time and attendance' WHERE scenario_id = '55.50.200.200';
UPDATE scenario_selection SET bpc_process = 'Manage employee travel', bpc_e2e = 'Manage time and attendance' WHERE scenario_id = '55.50.200.301';
UPDATE scenario_selection SET bpc_process = 'Manage employee travel', bpc_e2e = 'Manage time and attendance' WHERE scenario_id = '55.50.200.302';
UPDATE scenario_selection SET bpc_process = 'Manage employee travel', bpc_e2e = 'Manage time and attendance' WHERE scenario_id = '55.50.200.303';
UPDATE scenario_selection SET bpc_process = 'Reimburse workers for expenses', bpc_e2e = 'Manage compensation and benefits' WHERE scenario_id = '55.70.045.100';
UPDATE scenario_selection SET bpc_process = 'Reimburse workers for expenses', bpc_e2e = 'Manage compensation and benefits' WHERE scenario_id = '55.70.045.300';
UPDATE scenario_selection SET bpc_process = 'Define accounts receivable strategy', bpc_e2e = 'Develop sales policies' WHERE scenario_id = '65.05.090.100';
UPDATE scenario_selection SET bpc_process = 'Define accounts receivable strategy', bpc_e2e = 'Develop sales policies' WHERE scenario_id = '65.05.090.200';
UPDATE scenario_selection SET bpc_process = 'Define accounts receivable strategy', bpc_e2e = 'Develop sales policies' WHERE scenario_id = '65.05.090.300';
UPDATE scenario_selection SET bpc_process = 'Define credit and collections strategy', bpc_e2e = 'Develop sales policies' WHERE scenario_id = '65.05.100.100';
UPDATE scenario_selection SET bpc_process = 'Define credit and collections strategy', bpc_e2e = 'Develop sales policies' WHERE scenario_id = '65.05.100.200';
UPDATE scenario_selection SET bpc_process = 'Define credit and collections strategy', bpc_e2e = 'Develop sales policies' WHERE scenario_id = '65.05.100.300';
UPDATE scenario_selection SET bpc_process = 'Define credit and collections strategy', bpc_e2e = 'Develop sales policies' WHERE scenario_id = '65.05.100.400';
UPDATE scenario_selection SET bpc_process = 'Issue sales invoices', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.010.100';
UPDATE scenario_selection SET bpc_process = 'Issue sales invoices', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.010.102';
UPDATE scenario_selection SET bpc_process = 'Issue sales invoices', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.010.103';
UPDATE scenario_selection SET bpc_process = 'Issue sales invoices', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.010.104';
UPDATE scenario_selection SET bpc_process = 'Issue sales invoices', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.010.105';
UPDATE scenario_selection SET bpc_process = 'Issue sales invoices', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.010.106';
UPDATE scenario_selection SET bpc_process = 'Issue sales invoices', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.010.107';
UPDATE scenario_selection SET bpc_process = 'Issue sales invoices', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.010.200';
UPDATE scenario_selection SET bpc_process = 'Issue sales invoices', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.010.300';
UPDATE scenario_selection SET bpc_process = 'Issue sales invoices', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.010.620';
UPDATE scenario_selection SET bpc_process = 'Issue sales invoices', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.010.630';
UPDATE scenario_selection SET bpc_process = 'Issue sales invoices', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.010.640';
UPDATE scenario_selection SET bpc_process = 'Issue customer credits', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.030.100';
UPDATE scenario_selection SET bpc_process = 'Issue customer credits', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.030.700';
UPDATE scenario_selection SET bpc_process = 'Issue customer credits', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.030.750';
UPDATE scenario_selection SET bpc_process = 'Issue customer credits', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.030.800';
UPDATE scenario_selection SET bpc_process = 'Bill subscriptions', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.050.300';
UPDATE scenario_selection SET bpc_process = 'Process customer payments', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.100.010';
UPDATE scenario_selection SET bpc_process = 'Process customer payments', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.100.040';
UPDATE scenario_selection SET bpc_process = 'Process customer payments', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.100.050';
UPDATE scenario_selection SET bpc_process = 'Process customer payments', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.100.060';
UPDATE scenario_selection SET bpc_process = 'Process customer payments', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.100.210';
UPDATE scenario_selection SET bpc_process = 'Process customer payments', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.100.220';
UPDATE scenario_selection SET bpc_process = 'Process customer payments', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.100.230';
UPDATE scenario_selection SET bpc_process = 'Process customer payments', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.100.240';
UPDATE scenario_selection SET bpc_process = 'Process customer prepayments', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.110.100';
UPDATE scenario_selection SET bpc_process = 'Process customer refunds', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.120.100';
UPDATE scenario_selection SET bpc_process = 'Process customer refunds', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.120.400';
UPDATE scenario_selection SET bpc_process = 'Settle customer transactions', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.130.100';
UPDATE scenario_selection SET bpc_process = 'Settle customer transactions', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.130.200';
UPDATE scenario_selection SET bpc_process = 'Settle customer transactions', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.130.400';
UPDATE scenario_selection SET bpc_process = 'Write off bad debt', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.200.100';
UPDATE scenario_selection SET bpc_process = 'Write off bad debt', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.200.200';
UPDATE scenario_selection SET bpc_process = 'Write off bad debt', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.200.300';
UPDATE scenario_selection SET bpc_process = 'Manage trade allowances', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.400.100';
UPDATE scenario_selection SET bpc_process = 'Manage trade allowances', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.400.200';
UPDATE scenario_selection SET bpc_process = 'Calculate sales commissions', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.500.100';
UPDATE scenario_selection SET bpc_process = 'Manage bills of exchange', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.600.100';
UPDATE scenario_selection SET bpc_process = 'Manage bills of exchange', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.600.200';
UPDATE scenario_selection SET bpc_process = 'Manage bills of exchange', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.600.300';
UPDATE scenario_selection SET bpc_process = 'Manage bills of exchange', bpc_e2e = 'Manage accounts receivable' WHERE scenario_id = '65.30.600.400';
UPDATE scenario_selection SET bpc_process = 'Assess customer credit risk', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.010.100';
UPDATE scenario_selection SET bpc_process = 'Assess customer credit risk', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.010.200';
UPDATE scenario_selection SET bpc_process = 'Assess customer credit risk', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.010.300';
UPDATE scenario_selection SET bpc_process = 'Manage customer holds', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.050.100';
UPDATE scenario_selection SET bpc_process = 'Manage customer holds', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.050.200';
UPDATE scenario_selection SET bpc_process = 'Monitor customer credit', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.060.100';
UPDATE scenario_selection SET bpc_process = 'Monitor customer credit', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.060.200';
UPDATE scenario_selection SET bpc_process = 'Monitor customer credit', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.060.300';
UPDATE scenario_selection SET bpc_process = 'Monitor customer credit', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.060.400';
UPDATE scenario_selection SET bpc_process = 'Collect interest', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.070.100';
UPDATE scenario_selection SET bpc_process = 'Collect interest', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.070.200';
UPDATE scenario_selection SET bpc_process = 'Manage customer collections', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.080.100';
UPDATE scenario_selection SET bpc_process = 'Manage customer collections', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.080.300';
UPDATE scenario_selection SET bpc_process = 'Manage customer collections', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.080.400';
UPDATE scenario_selection SET bpc_process = 'Manage customer collections', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.080.500';
UPDATE scenario_selection SET bpc_process = 'Manage customer collections', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.080.600';
UPDATE scenario_selection SET bpc_process = 'Manage customer collections', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.080.700';
UPDATE scenario_selection SET bpc_process = 'Manage customer collections', bpc_e2e = 'Manage credit and collections' WHERE scenario_id = '65.50.080.800';
UPDATE scenario_selection SET bpc_process = 'Analyze accounts receivable', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.200.100';
UPDATE scenario_selection SET bpc_process = 'Analyze accounts receivable', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.200.200';
UPDATE scenario_selection SET bpc_process = 'Analyze accounts receivable', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.200.300';
UPDATE scenario_selection SET bpc_process = 'Analyze accounts receivable', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.200.400';
UPDATE scenario_selection SET bpc_process = 'Analyze accounts receivable', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.200.500';
UPDATE scenario_selection SET bpc_process = 'Analyze accounts receivable', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.200.600';
UPDATE scenario_selection SET bpc_process = 'Analyze cash flow', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.300.100';
UPDATE scenario_selection SET bpc_process = 'Analyze cash flow', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.300.200';
UPDATE scenario_selection SET bpc_process = 'Analyze cash flow', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.300.300';
UPDATE scenario_selection SET bpc_process = 'Analyze cash flow', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.300.302';
UPDATE scenario_selection SET bpc_process = 'Analyze customer risk', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.400.100';
UPDATE scenario_selection SET bpc_process = 'Analyze revenue', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.500.100';
UPDATE scenario_selection SET bpc_process = 'Analyze revenue', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.500.125';
UPDATE scenario_selection SET bpc_process = 'Analyze revenue', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.500.150';
UPDATE scenario_selection SET bpc_process = 'Analyze revenue', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.500.175';
UPDATE scenario_selection SET bpc_process = 'Analyze revenue', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.500.200';
UPDATE scenario_selection SET bpc_process = 'Analyze revenue', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.500.250';
UPDATE scenario_selection SET bpc_process = 'Analyze revenue', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.500.300';
UPDATE scenario_selection SET bpc_process = 'Analyze revenue', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.500.400';
UPDATE scenario_selection SET bpc_process = 'Analyze revenue', bpc_e2e = 'Analyze sales performance' WHERE scenario_id = '65.60.500.500';
UPDATE scenario_selection SET bpc_process = 'Convert projects to fixed assets', bpc_e2e = 'Manage project financials' WHERE scenario_id = '80.50.040.100';
UPDATE scenario_selection SET bpc_process = 'Convert projects to fixed assets', bpc_e2e = 'Manage project financials' WHERE scenario_id = '80.50.040.200';
UPDATE scenario_selection SET bpc_process = 'Convert projects to fixed assets', bpc_e2e = 'Manage project financials' WHERE scenario_id = '80.50.040.300';
UPDATE scenario_selection SET bpc_process = 'Develop company structure', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.010.100';
UPDATE scenario_selection SET bpc_process = 'Develop company structure', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.010.200';
UPDATE scenario_selection SET bpc_process = 'Develop company structure', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.010.300';
UPDATE scenario_selection SET bpc_process = 'Develop company structure', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.010.400';
UPDATE scenario_selection SET bpc_process = 'Develop company structure', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.010.500';
UPDATE scenario_selection SET bpc_process = 'Develop company structure', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.010.600';
UPDATE scenario_selection SET bpc_process = 'Develop company structure', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.010.700';
UPDATE scenario_selection SET bpc_process = 'Develop company structure', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.010.725';
UPDATE scenario_selection SET bpc_process = 'Develop company structure', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.010.750';
UPDATE scenario_selection SET bpc_process = 'Develop company structure', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.010.775';
UPDATE scenario_selection SET bpc_process = 'Develop financial period strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.020.100';
UPDATE scenario_selection SET bpc_process = 'Develop financial period strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.020.200';
UPDATE scenario_selection SET bpc_process = 'Develop financial period strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.020.300';
UPDATE scenario_selection SET bpc_process = 'Develop financial period strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.020.400';
UPDATE scenario_selection SET bpc_process = 'Develop financial period strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.020.500';
UPDATE scenario_selection SET bpc_process = 'Develop financial period strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.020.600';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.100';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.110';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.200';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.210';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.300';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.310';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.400';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.410';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.500';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.510';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.600';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.610';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.700';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.800';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.900';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.910';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.920';
UPDATE scenario_selection SET bpc_process = 'Define posting policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.035.930';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.100';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.200';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.300';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.400';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.500';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.600';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.700';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.800';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.825';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.850';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.875';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.900';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.925';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.950';
UPDATE scenario_selection SET bpc_process = 'Develop chart of accounts strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.040.975';
UPDATE scenario_selection SET bpc_process = 'Develop budgeting strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.045.100';
UPDATE scenario_selection SET bpc_process = 'Develop budgeting strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.045.200';
UPDATE scenario_selection SET bpc_process = 'Develop budgeting strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.045.300';
UPDATE scenario_selection SET bpc_process = 'Develop currency policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.050.100';
UPDATE scenario_selection SET bpc_process = 'Develop currency policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.050.200';
UPDATE scenario_selection SET bpc_process = 'Develop currency policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.050.300';
UPDATE scenario_selection SET bpc_process = 'Develop currency policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.050.400';
UPDATE scenario_selection SET bpc_process = 'Develop currency policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.050.500';
UPDATE scenario_selection SET bpc_process = 'Develop currency policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.050.600';
UPDATE scenario_selection SET bpc_process = 'Develop currency policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.050.700';
UPDATE scenario_selection SET bpc_process = 'Develop currency policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.050.800';
UPDATE scenario_selection SET bpc_process = 'Develop currency policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.050.900';
UPDATE scenario_selection SET bpc_process = 'Develop currency policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.050.910';
UPDATE scenario_selection SET bpc_process = 'Develop currency policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.050.920';
UPDATE scenario_selection SET bpc_process = 'Develop currency policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.050.930';
UPDATE scenario_selection SET bpc_process = 'Develop currency policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.050.940';
UPDATE scenario_selection SET bpc_process = 'Define banking policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.060.100';
UPDATE scenario_selection SET bpc_process = 'Define banking policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.060.200';
UPDATE scenario_selection SET bpc_process = 'Define banking policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.060.300';
UPDATE scenario_selection SET bpc_process = 'Define banking policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.060.400';
UPDATE scenario_selection SET bpc_process = 'Define costing policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.075.100';
UPDATE scenario_selection SET bpc_process = 'Define costing policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.075.200';
UPDATE scenario_selection SET bpc_process = 'Define costing policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.075.300';
UPDATE scenario_selection SET bpc_process = 'Define costing policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.075.400';
UPDATE scenario_selection SET bpc_process = 'Define costing policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.075.500';
UPDATE scenario_selection SET bpc_process = 'Develop asset policies', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.100.100';
UPDATE scenario_selection SET bpc_process = 'Develop tax strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.200.100';
UPDATE scenario_selection SET bpc_process = 'Develop tax strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.200.200';
UPDATE scenario_selection SET bpc_process = 'Develop tax strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.200.300';
UPDATE scenario_selection SET bpc_process = 'Develop tax strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.200.400';
UPDATE scenario_selection SET bpc_process = 'Develop tax strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.200.500';
UPDATE scenario_selection SET bpc_process = 'Develop tax strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.200.600';
UPDATE scenario_selection SET bpc_process = 'Develop tax strategy', bpc_e2e = 'Define accounting policies' WHERE scenario_id = '90.10.200.700';
UPDATE scenario_selection SET bpc_process = 'Establish banking relationships', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.100.100';
UPDATE scenario_selection SET bpc_process = 'Establish banking relationships', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.100.200';
UPDATE scenario_selection SET bpc_process = 'Establish banking relationships', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.100.300';
UPDATE scenario_selection SET bpc_process = 'Establish banking relationships', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.100.400';
UPDATE scenario_selection SET bpc_process = 'Establish banking relationships', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.100.500';
UPDATE scenario_selection SET bpc_process = 'Establish banking relationships', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.100.600';
UPDATE scenario_selection SET bpc_process = 'Establish banking relationships', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.100.700';
UPDATE scenario_selection SET bpc_process = 'Reconcile bank accounts', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.200.100';
UPDATE scenario_selection SET bpc_process = 'Reconcile bank accounts', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.200.200';
UPDATE scenario_selection SET bpc_process = 'Forecast cash flow', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.300.010';
UPDATE scenario_selection SET bpc_process = 'Forecast cash flow', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.300.050';
UPDATE scenario_selection SET bpc_process = 'Forecast cash flow', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.300.100';
UPDATE scenario_selection SET bpc_process = 'Forecast cash flow', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.300.200';
UPDATE scenario_selection SET bpc_process = 'Forecast cash flow', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.300.300';
UPDATE scenario_selection SET bpc_process = 'Forecast cash flow', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.300.400';
UPDATE scenario_selection SET bpc_process = 'Forecast cash flow', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.300.500';
UPDATE scenario_selection SET bpc_process = 'Forecast cash flow', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.300.600';
UPDATE scenario_selection SET bpc_process = 'Track cash position', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.400.100';
UPDATE scenario_selection SET bpc_process = 'Track cash position', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.400.200';
UPDATE scenario_selection SET bpc_process = 'Track cash position', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.400.300';
UPDATE scenario_selection SET bpc_process = 'Track cash position', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.400.400';
UPDATE scenario_selection SET bpc_process = 'Track cash position', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.400.500';
UPDATE scenario_selection SET bpc_process = 'Track cash position', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.400.600';
UPDATE scenario_selection SET bpc_process = 'Track cash position', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.400.700';
UPDATE scenario_selection SET bpc_process = 'Track cash position', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.400.800';
UPDATE scenario_selection SET bpc_process = 'Predict customer payments', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.500.100';
UPDATE scenario_selection SET bpc_process = 'Manage funds', bpc_e2e = 'Manage cash' WHERE scenario_id = '90.25.600.100';
UPDATE scenario_selection SET bpc_process = 'Plan budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.020.100';
UPDATE scenario_selection SET bpc_process = 'Plan budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.020.200';
UPDATE scenario_selection SET bpc_process = 'Plan budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.020.300';
UPDATE scenario_selection SET bpc_process = 'Plan budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.020.400';
UPDATE scenario_selection SET bpc_process = 'Plan budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.020.500';
UPDATE scenario_selection SET bpc_process = 'Plan budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.020.600';
UPDATE scenario_selection SET bpc_process = 'Plan budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.020.700';
UPDATE scenario_selection SET bpc_process = 'Define preliminary budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.025.100';
UPDATE scenario_selection SET bpc_process = 'Reserve budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.030.100';
UPDATE scenario_selection SET bpc_process = 'Allocate budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.040.100';
UPDATE scenario_selection SET bpc_process = 'Allocate budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.040.200';
UPDATE scenario_selection SET bpc_process = 'Maintain budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.050.100';
UPDATE scenario_selection SET bpc_process = 'Maintain budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.050.200';
UPDATE scenario_selection SET bpc_process = 'Maintain budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.050.202';
UPDATE scenario_selection SET bpc_process = 'Maintain budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.050.300';
UPDATE scenario_selection SET bpc_process = 'Maintain budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.050.350';
UPDATE scenario_selection SET bpc_process = 'Maintain budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.050.400';
UPDATE scenario_selection SET bpc_process = 'Maintain budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.050.500';
UPDATE scenario_selection SET bpc_process = 'Maintain budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.050.600';
UPDATE scenario_selection SET bpc_process = 'Maintain budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.050.700';
UPDATE scenario_selection SET bpc_process = 'Approve budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.060.100';
UPDATE scenario_selection SET bpc_process = 'Approve budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.060.200';
UPDATE scenario_selection SET bpc_process = 'Transfer budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.070.100';
UPDATE scenario_selection SET bpc_process = 'Transfer budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.070.200';
UPDATE scenario_selection SET bpc_process = 'Transfer budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.070.300';
UPDATE scenario_selection SET bpc_process = 'Appropriate budgets', bpc_e2e = 'Manage budgets' WHERE scenario_id = '90.30.080.100';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.050';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.150';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.250';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.275';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.300';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.325';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.375';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.400';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.425';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.450';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.475';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.500';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.601';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.602';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.603';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.604';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.605';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.606';
UPDATE scenario_selection SET bpc_process = 'Record ledger entries', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.040.607';
UPDATE scenario_selection SET bpc_process = 'Record intercompany transactions', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.043.100';
UPDATE scenario_selection SET bpc_process = 'Record cost accounting transactions', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.045.100';
UPDATE scenario_selection SET bpc_process = 'Record cost accounting transactions', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.045.200';
UPDATE scenario_selection SET bpc_process = 'Record cost accounting transactions', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.045.300';
UPDATE scenario_selection SET bpc_process = 'Revalue inventory', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.048.100';
UPDATE scenario_selection SET bpc_process = 'Revalue inventory', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.048.200';
UPDATE scenario_selection SET bpc_process = 'Revalue inventory', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.048.300';
UPDATE scenario_selection SET bpc_process = 'Revalue inventory', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.048.400';
UPDATE scenario_selection SET bpc_process = 'Correct ledger vouchers', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.050.100';
UPDATE scenario_selection SET bpc_process = 'Correct ledger vouchers', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.050.200';
UPDATE scenario_selection SET bpc_process = 'Manage accruals', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.060.100';
UPDATE scenario_selection SET bpc_process = 'Manage accruals', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.060.200';
UPDATE scenario_selection SET bpc_process = 'Manage accruals', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.060.300';
UPDATE scenario_selection SET bpc_process = 'Manage accruals', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.060.400';
UPDATE scenario_selection SET bpc_process = 'Manage accruals', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.060.500';
UPDATE scenario_selection SET bpc_process = 'Manage deferrals', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.070.100';
UPDATE scenario_selection SET bpc_process = 'Manage deferrals', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.070.200';
UPDATE scenario_selection SET bpc_process = 'Process allocations', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.080.100';
UPDATE scenario_selection SET bpc_process = 'Process allocations', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.080.200';
UPDATE scenario_selection SET bpc_process = 'Record tax commitments', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.090.100';
UPDATE scenario_selection SET bpc_process = 'Record tax commitments', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.090.200';
UPDATE scenario_selection SET bpc_process = 'Record tax commitments', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.090.300';
UPDATE scenario_selection SET bpc_process = 'Pay taxes', bpc_e2e = 'Record financial transactions' WHERE scenario_id = '90.50.100.100';
UPDATE scenario_selection SET bpc_process = 'Finalize and post transactions', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.020.100';
UPDATE scenario_selection SET bpc_process = 'Finalize and post transactions', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.020.200';
UPDATE scenario_selection SET bpc_process = 'Finalize and post transactions', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.020.300';
UPDATE scenario_selection SET bpc_process = 'Finalize and post transactions', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.020.400';
UPDATE scenario_selection SET bpc_process = 'Finalize and post transactions', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.020.500';
UPDATE scenario_selection SET bpc_process = 'Reconcile ledger and subledger', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.040.100';
UPDATE scenario_selection SET bpc_process = 'Reconcile ledger and subledger', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.040.200';
UPDATE scenario_selection SET bpc_process = 'Reconcile ledger and subledger', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.040.300';
UPDATE scenario_selection SET bpc_process = 'Reconcile ledger and subledger', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.040.400';
UPDATE scenario_selection SET bpc_process = 'Reconcile ledger and subledger', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.040.500';
UPDATE scenario_selection SET bpc_process = 'Reconcile ledger and subledger', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.040.600';
UPDATE scenario_selection SET bpc_process = 'Reconcile ledger and subledger', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.040.700';
UPDATE scenario_selection SET bpc_process = 'Reconcile ledger and subledger', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.040.800';
UPDATE scenario_selection SET bpc_process = 'Revalue currency', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.060.100';
UPDATE scenario_selection SET bpc_process = 'Revalue currency', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.060.200';
UPDATE scenario_selection SET bpc_process = 'Revalue currency', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.060.300';
UPDATE scenario_selection SET bpc_process = 'Revalue currency', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.060.400';
UPDATE scenario_selection SET bpc_process = 'Perform ledger settlements', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.070.100';
UPDATE scenario_selection SET bpc_process = 'Perform ledger settlements', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.070.200';
UPDATE scenario_selection SET bpc_process = 'Consolidate and eliminate financials', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.080.100';
UPDATE scenario_selection SET bpc_process = 'Consolidate and eliminate financials', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.080.200';
UPDATE scenario_selection SET bpc_process = 'Consolidate and eliminate financials', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.080.300';
UPDATE scenario_selection SET bpc_process = 'Consolidate and eliminate financials', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.080.400';
UPDATE scenario_selection SET bpc_process = 'Consolidate and eliminate financials', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.080.500';
UPDATE scenario_selection SET bpc_process = 'Prepare financial statements', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.090.100';
UPDATE scenario_selection SET bpc_process = 'Prepare financial statements', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.090.150';
UPDATE scenario_selection SET bpc_process = 'Prepare financial statements', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.090.200';
UPDATE scenario_selection SET bpc_process = 'Prepare financial statements', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.090.300';
UPDATE scenario_selection SET bpc_process = 'Prepare financial statements', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.090.400';
UPDATE scenario_selection SET bpc_process = 'Prepare financial statements', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.090.500';
UPDATE scenario_selection SET bpc_process = 'Prepare financial statements', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.090.600';
UPDATE scenario_selection SET bpc_process = 'Prepare financial statements', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.090.700';
UPDATE scenario_selection SET bpc_process = 'Prepare financial statements', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.090.800';
UPDATE scenario_selection SET bpc_process = 'Prepare statutory financial reports', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.095.100';
UPDATE scenario_selection SET bpc_process = 'Prepare statutory financial reports', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.095.101';
UPDATE scenario_selection SET bpc_process = 'Close periods', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.100.100';
UPDATE scenario_selection SET bpc_process = 'Close periods', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.100.200';
UPDATE scenario_selection SET bpc_process = 'Close periods', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.100.300';
UPDATE scenario_selection SET bpc_process = 'Close periods', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.100.400';
UPDATE scenario_selection SET bpc_process = 'Close periods', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.100.500';
UPDATE scenario_selection SET bpc_process = 'Close periods', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.100.600';
UPDATE scenario_selection SET bpc_process = 'Close periods', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.100.700';
UPDATE scenario_selection SET bpc_process = 'Close periods', bpc_e2e = 'Close financial periods' WHERE scenario_id = '90.60.100.800';
UPDATE scenario_selection SET bpc_process = 'Audit financial transactions', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.005.100';
UPDATE scenario_selection SET bpc_process = 'Audit financial transactions', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.005.200';
UPDATE scenario_selection SET bpc_process = 'Audit financial transactions', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.005.300';
UPDATE scenario_selection SET bpc_process = 'Audit financial transactions', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.005.400';
UPDATE scenario_selection SET bpc_process = 'Audit financial transactions', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.005.500';
UPDATE scenario_selection SET bpc_process = 'Audit financial transactions', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.005.600';
UPDATE scenario_selection SET bpc_process = 'Analyze costs', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.065.100';
UPDATE scenario_selection SET bpc_process = 'Analyze costs', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.065.300';
UPDATE scenario_selection SET bpc_process = 'Analyze costs', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.065.400';
UPDATE scenario_selection SET bpc_process = 'Analyze costs', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.065.500';
UPDATE scenario_selection SET bpc_process = 'Analyze costs', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.065.600';
UPDATE scenario_selection SET bpc_process = 'Analyze costs', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.065.700';
UPDATE scenario_selection SET bpc_process = 'Monitor budget to actuals', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.070.100';
UPDATE scenario_selection SET bpc_process = 'Monitor budget to actuals', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.070.200';
UPDATE scenario_selection SET bpc_process = 'Analyze financial statements', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.110.100';
UPDATE scenario_selection SET bpc_process = 'Analyze financial statements', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.110.200';
UPDATE scenario_selection SET bpc_process = 'Analyze financial statements', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.110.300';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.100';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.200';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.300';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.400';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.500';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.600';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.700';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.701';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.702';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.703';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.704';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.705';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.706';
UPDATE scenario_selection SET bpc_process = 'Audit financial results', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.120.707';
UPDATE scenario_selection SET bpc_process = 'Monitor financial ratios and metrics', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.200.100';
UPDATE scenario_selection SET bpc_process = 'Monitor regulatory compliance', bpc_e2e = 'Analyze financial performance' WHERE scenario_id = '90.70.300.100';
UPDATE scenario_selection SET bpc_process = 'Define accounts payable policies', bpc_e2e = 'Develop procurement and sourcing strategy' WHERE scenario_id = '75.10.015.100';
UPDATE scenario_selection SET bpc_process = 'Define accounts payable policies', bpc_e2e = 'Develop procurement and sourcing strategy' WHERE scenario_id = '75.10.015.200';
UPDATE scenario_selection SET bpc_process = 'Define accounts payable policies', bpc_e2e = 'Develop procurement and sourcing strategy' WHERE scenario_id = '75.10.015.300';
UPDATE scenario_selection SET bpc_process = 'Analyze sourcing market', bpc_e2e = 'Develop procurement and sourcing strategy' WHERE scenario_id = '75.10.070.100';
UPDATE scenario_selection SET bpc_process = 'Track supplier certifications and compliance', bpc_e2e = 'Manage supplier relationships' WHERE scenario_id = '75.30.050.100';
UPDATE scenario_selection SET bpc_process = 'Track supplier certifications and compliance', bpc_e2e = 'Manage supplier relationships' WHERE scenario_id = '75.30.050.201';
UPDATE scenario_selection SET bpc_process = 'Track supplier certifications and compliance', bpc_e2e = 'Manage supplier relationships' WHERE scenario_id = '75.30.050.400';
UPDATE scenario_selection SET bpc_process = 'Process supplier invoices', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.020.100';
UPDATE scenario_selection SET bpc_process = 'Process supplier invoices', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.020.101';
UPDATE scenario_selection SET bpc_process = 'Process supplier invoices', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.020.200';
UPDATE scenario_selection SET bpc_process = 'Process supplier invoices', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.020.300';
UPDATE scenario_selection SET bpc_process = 'Process supplier invoices', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.020.400';
UPDATE scenario_selection SET bpc_process = 'Process supplier invoices', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.020.500';
UPDATE scenario_selection SET bpc_process = 'Process supplier invoices', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.020.600';
UPDATE scenario_selection SET bpc_process = 'Process supplier invoices', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.020.700';
UPDATE scenario_selection SET bpc_process = 'Process supplier invoices', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.020.800';
UPDATE scenario_selection SET bpc_process = 'Process supplier invoices', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.020.900';
UPDATE scenario_selection SET bpc_process = 'Issue and settle supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.090.100';
UPDATE scenario_selection SET bpc_process = 'Issue and settle supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.090.200';
UPDATE scenario_selection SET bpc_process = 'Issue and settle supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.090.210';
UPDATE scenario_selection SET bpc_process = 'Issue and settle supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.090.220';
UPDATE scenario_selection SET bpc_process = 'Issue and settle supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.090.230';
UPDATE scenario_selection SET bpc_process = 'Issue and settle supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.090.300';
UPDATE scenario_selection SET bpc_process = 'Issue and settle supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.090.400';
UPDATE scenario_selection SET bpc_process = 'Issue and settle supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.090.500';
UPDATE scenario_selection SET bpc_process = 'Issue and settle supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.090.600';
UPDATE scenario_selection SET bpc_process = 'Issue and settle supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.090.700';
UPDATE scenario_selection SET bpc_process = 'Issue and settle supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.090.800';
UPDATE scenario_selection SET bpc_process = 'Manage promissory notes', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.100.100';
UPDATE scenario_selection SET bpc_process = 'Manage promissory notes', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.100.200';
UPDATE scenario_selection SET bpc_process = 'Manage promissory notes', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.100.300';
UPDATE scenario_selection SET bpc_process = 'Manage promissory notes', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.100.400';
UPDATE scenario_selection SET bpc_process = 'Manage promissory notes', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.100.500';
UPDATE scenario_selection SET bpc_process = 'Manage promissory notes', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.100.600';
UPDATE scenario_selection SET bpc_process = 'Manage promissory notes', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.100.700';
UPDATE scenario_selection SET bpc_process = 'Cancel supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.110.100';
UPDATE scenario_selection SET bpc_process = 'Cancel supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.110.200';
UPDATE scenario_selection SET bpc_process = 'Cancel supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.110.300';
UPDATE scenario_selection SET bpc_process = 'Correct supplier payments', bpc_e2e = 'Manage accounts payable' WHERE scenario_id = '75.50.120.100';
UPDATE scenario_selection SET bpc_process = 'Manage supplier performance', bpc_e2e = 'Analyze procurement and sourcing' WHERE scenario_id = '75.80.020.600';
UPDATE scenario_selection SET bpc_process = 'Analyze account payable', bpc_e2e = 'Analyze procurement and sourcing' WHERE scenario_id = '75.80.050.100';
UPDATE scenario_selection SET bpc_process = 'Analyze account payable', bpc_e2e = 'Analyze procurement and sourcing' WHERE scenario_id = '75.80.050.200';
UPDATE scenario_selection SET bpc_process = 'Analyze account payable', bpc_e2e = 'Analyze procurement and sourcing' WHERE scenario_id = '75.80.050.300';
UPDATE scenario_selection SET bpc_process = 'Analyze account payable', bpc_e2e = 'Analyze procurement and sourcing' WHERE scenario_id = '75.80.050.400';
UPDATE scenario_selection SET bpc_process = 'Analyze account payable', bpc_e2e = 'Analyze procurement and sourcing' WHERE scenario_id = '75.80.050.450';
UPDATE scenario_selection SET bpc_process = 'Analyze account payable', bpc_e2e = 'Analyze procurement and sourcing' WHERE scenario_id = '75.80.050.500';
UPDATE scenario_selection SET bpc_process = 'Analyze account payable', bpc_e2e = 'Analyze procurement and sourcing' WHERE scenario_id = '75.80.050.600';
UPDATE scenario_selection SET bpc_process = 'Analyze account payable', bpc_e2e = 'Analyze procurement and sourcing' WHERE scenario_id = '75.80.050.700';
UPDATE scenario_selection SET bpc_process = 'Analyze account payable', bpc_e2e = 'Analyze procurement and sourcing' WHERE scenario_id = '75.80.050.800';
UPDATE scenario_selection SET bpc_process = 'Analyze account payable', bpc_e2e = 'Analyze procurement and sourcing' WHERE scenario_id = '75.80.050.900';
UPDATE scenario_selection SET bpc_process = 'Analyze account payable', bpc_e2e = 'Analyze procurement and sourcing' WHERE scenario_id = '75.80.050.950';